### ISSUE TITLE
Limit axes for performance?

### ISSUE THREAD

**Issue by gyopiazza** [chrisbateman/impetus#11]
First of all thanks for this little gem. It runs incredibly smooth and I was wondering if it makes sense to add a setting which limits the scrolling axes (x, y or both) to improve the performance even more when just one axis is needed.

Thank you!

**Comment by chrisbateman** [comment]
Thank you very much, I appreciate the compliment!

This is a good thought, but I'm guessing that it may not make a notable difference. In the spirit of avoiding premature optimization, I'll hold off on this unless there's some data to show otherwise.
