### ISSUE TITLE
[Violation] Added non-passive event

### ISSUE THREAD

**Issue by dy** [chrisbateman/impetus#39]
To avoid unnecessary warning in console, [this](https://github.com/chrisbateman/impetus/blob/master/src/Impetus.js#L9) and all other touch event listeners can be modified to 

```js
window.addEventListener('touchstart', fn, hasPassive ? { passive: true } : false)
```

for `hasPassive` can a modernizr-like detector be used or [has-passive-events](https://ghub.io/has-passive-events) package.

**Comment by weotch** [comment]
@dy I think this can be closed now, it looks like support was added in https://github.com/chrisbateman/impetus/commit/d5d023aa6085f5a46637f31bb823f94ac21cdac5

**Comment by dy** [comment]
Great!
