### ISSUE TITLE
Bounds rubber-banding

### ISSUE THREAD

**Issue by abusedmedia** [chrisbateman/impetus#8]
Hi there
Thanks for this very useful library.
I'm wondering if it would be possible to add a kind of negative inertia when bounds are defined thus the x/y props would be smoothly slowed down and bounced back to the bound value instead stopped immediately.

**Comment by yckart** [comment]
:+1:

**Comment by chrisbateman** [comment]
Definitely wouldn't mind adding this - I'll try to get around to it...

**Comment by RuudBurger** [comment]
I'd like this as well ;) so just a +1

**Comment by chrisbateman** [comment]
I added this in a separate branch - https://github.com/chrisbateman/impetus/tree/bounce

Please try it out if you can and let me know how it goes. Probably still needs some tweaking.

**Comment by abusedmedia** [comment]
Very nice Chris!
Just tested briefly and it looks very good.
I would only add a cumulative friction during drag in order to slow down until stop after a while...
You can check my quick&dirty implementation about what I mean, here:
https://github.com/abusedmedia/impetus/blob/bounce/impetus.js#L208-L211

Thank you!

**Comment by chrisbateman** [comment]
@abusedmedia Added that in the bounce branch. Still might want to tweak some of the overall physics a bit...

**Comment by chrisbateman** [comment]
Anybody have a preference on whether this should be enabled by default? My thought is yes...

**Comment by chrisbateman** [comment]
Implemented as of v0.8.0

**Comment by pyrsmk** [comment]
:+1:
